sudo: false
language: node_js
node_js:
  - "v5"
  - "v4"
  - "0.12"
  - "0.10"
  - "0.8"
before_install:
  - curl --location http://git.io/1OcIZA | bash -s
branches:
  only:
    - master
matrix:
  allow_failures:
    - node_js: 0.8
notifications:
  email:
    - travis@nodejitsu.com
  irc: "irc.freenode.org#nodejitsu"
